version: “3.8”
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongod
  nginx:
    build: ./nginx/development
    container_name: nginx
    depends_on:
      - mongo
    ports:
      - '80:80'
    volumes:
      - ./nginx/development/nginx.conf:/etc/nginx/nginx.conf