version: “3.8”
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongod
  golang:
    build: .
    depends_on:
      - mongo
    command: 
      go run main.go
    ports:
      - '8080:8080'
    volumes:
      - storage:/go/tmp/src/mongo-golang/storage
  nginx:
    build: nginx
    depends_on:
      - golang
      - mongo
    ports:
      - '80:80'
    volumes:
      - storage:/var/html/storage/
volumes:
  storage: